// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsequencer.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSequencer_CfgInitialize(XSequencer *InstancePtr, XSequencer_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSequencer_Start(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSequencer_IsDone(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSequencer_IsIdle(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSequencer_IsReady(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSequencer_EnableAutoRestart(XSequencer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XSequencer_DisableAutoRestart(XSequencer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_AP_CTRL, 0);
}

void XSequencer_Set_C_table_A(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_A_DATA, Data);
}

u32 XSequencer_Get_C_table_A(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_A_DATA);
    return Data;
}

void XSequencer_Set_C_table_C(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_C_DATA, Data);
}

u32 XSequencer_Get_C_table_C(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_C_DATA);
    return Data;
}

void XSequencer_Set_C_table_G(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_G_DATA, Data);
}

u32 XSequencer_Get_C_table_G(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_G_DATA);
    return Data;
}

void XSequencer_Set_C_table_T(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_T_DATA, Data);
}

u32 XSequencer_Get_C_table_T(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_C_TABLE_T_DATA);
    return Data;
}

void XSequencer_Set_I_table(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_I_TABLE_DATA, Data);
}

u32 XSequencer_Get_I_table(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_I_TABLE_DATA);
    return Data;
}

void XSequencer_Set_SR_length(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_SR_LENGTH_DATA, Data);
}

u32 XSequencer_Get_SR_length(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_SR_LENGTH_DATA);
    return Data;
}

void XSequencer_Set_ref_length(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_REF_LENGTH_DATA, Data);
}

u32 XSequencer_Get_ref_length(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_REF_LENGTH_DATA);
    return Data;
}

void XSequencer_Set_SR(XSequencer *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_SR_DATA, Data);
}

u32 XSequencer_Get_SR(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_SR_DATA);
    return Data;
}

u32 XSequencer_Get_done(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_DONE_DATA);
    return Data;
}

u32 XSequencer_Get_done_vld(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_DONE_CTRL);
    return Data & 0x1;
}

u32 XSequencer_Get_matched(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_MATCHED_DATA);
    return Data;
}

u32 XSequencer_Get_matched_vld(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_MATCHED_CTRL);
    return Data & 0x1;
}

u32 XSequencer_Get_final_top_ptr(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_FINAL_TOP_PTR_DATA);
    return Data;
}

u32 XSequencer_Get_final_top_ptr_vld(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_FINAL_TOP_PTR_CTRL);
    return Data & 0x1;
}

u32 XSequencer_Get_final_bot_ptr(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_FINAL_BOT_PTR_DATA);
    return Data;
}

u32 XSequencer_Get_final_bot_ptr_vld(XSequencer *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_FINAL_BOT_PTR_CTRL);
    return Data & 0x1;
}

void XSequencer_InterruptGlobalEnable(XSequencer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_GIE, 1);
}

void XSequencer_InterruptGlobalDisable(XSequencer *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_GIE, 0);
}

void XSequencer_InterruptEnable(XSequencer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_IER);
    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_IER, Register | Mask);
}

void XSequencer_InterruptDisable(XSequencer *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_IER);
    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XSequencer_InterruptClear(XSequencer *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSequencer_WriteReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_ISR, Mask);
}

u32 XSequencer_InterruptGetEnabled(XSequencer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_IER);
}

u32 XSequencer_InterruptGetStatus(XSequencer *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSequencer_ReadReg(InstancePtr->Axilites_BaseAddress, XSEQUENCER_AXILITES_ADDR_ISR);
}

