// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsequencer.h"

extern XSequencer_Config XSequencer_ConfigTable[];

XSequencer_Config *XSequencer_LookupConfig(u16 DeviceId) {
	XSequencer_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSEQUENCER_NUM_INSTANCES; Index++) {
		if (XSequencer_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSequencer_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSequencer_Initialize(XSequencer *InstancePtr, u16 DeviceId) {
	XSequencer_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSequencer_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSequencer_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

