// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of C_table_A
//        bit 31~0 - C_table_A[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of C_table_C
//        bit 31~0 - C_table_C[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of C_table_G
//        bit 31~0 - C_table_G[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of C_table_T
//        bit 31~0 - C_table_T[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of I_table
//        bit 31~0 - I_table[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of SR_length
//        bit 31~0 - SR_length[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of ref_length
//        bit 31~0 - ref_length[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of SR
//        bit 31~0 - SR[31:0] (Read/Write)
// 0x4c : reserved
// 0x50 : Data signal of done
//        bit 31~0 - done[31:0] (Read)
// 0x54 : Control signal of done
//        bit 0  - done_ap_vld (Read/COR)
//        others - reserved
// 0x58 : Data signal of matched
//        bit 31~0 - matched[31:0] (Read)
// 0x5c : Control signal of matched
//        bit 0  - matched_ap_vld (Read/COR)
//        others - reserved
// 0x60 : Data signal of final_top_ptr
//        bit 31~0 - final_top_ptr[31:0] (Read)
// 0x64 : Control signal of final_top_ptr
//        bit 0  - final_top_ptr_ap_vld (Read/COR)
//        others - reserved
// 0x68 : Data signal of final_bot_ptr
//        bit 31~0 - final_bot_ptr[31:0] (Read)
// 0x6c : Control signal of final_bot_ptr
//        bit 0  - final_bot_ptr_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSEQUENCER_AXILITES_ADDR_AP_CTRL            0x00
#define XSEQUENCER_AXILITES_ADDR_GIE                0x04
#define XSEQUENCER_AXILITES_ADDR_IER                0x08
#define XSEQUENCER_AXILITES_ADDR_ISR                0x0c
#define XSEQUENCER_AXILITES_ADDR_C_TABLE_A_DATA     0x10
#define XSEQUENCER_AXILITES_BITS_C_TABLE_A_DATA     32
#define XSEQUENCER_AXILITES_ADDR_C_TABLE_C_DATA     0x18
#define XSEQUENCER_AXILITES_BITS_C_TABLE_C_DATA     32
#define XSEQUENCER_AXILITES_ADDR_C_TABLE_G_DATA     0x20
#define XSEQUENCER_AXILITES_BITS_C_TABLE_G_DATA     32
#define XSEQUENCER_AXILITES_ADDR_C_TABLE_T_DATA     0x28
#define XSEQUENCER_AXILITES_BITS_C_TABLE_T_DATA     32
#define XSEQUENCER_AXILITES_ADDR_I_TABLE_DATA       0x30
#define XSEQUENCER_AXILITES_BITS_I_TABLE_DATA       32
#define XSEQUENCER_AXILITES_ADDR_SR_LENGTH_DATA     0x38
#define XSEQUENCER_AXILITES_BITS_SR_LENGTH_DATA     32
#define XSEQUENCER_AXILITES_ADDR_REF_LENGTH_DATA    0x40
#define XSEQUENCER_AXILITES_BITS_REF_LENGTH_DATA    32
#define XSEQUENCER_AXILITES_ADDR_SR_DATA            0x48
#define XSEQUENCER_AXILITES_BITS_SR_DATA            32
#define XSEQUENCER_AXILITES_ADDR_DONE_DATA          0x50
#define XSEQUENCER_AXILITES_BITS_DONE_DATA          32
#define XSEQUENCER_AXILITES_ADDR_DONE_CTRL          0x54
#define XSEQUENCER_AXILITES_ADDR_MATCHED_DATA       0x58
#define XSEQUENCER_AXILITES_BITS_MATCHED_DATA       32
#define XSEQUENCER_AXILITES_ADDR_MATCHED_CTRL       0x5c
#define XSEQUENCER_AXILITES_ADDR_FINAL_TOP_PTR_DATA 0x60
#define XSEQUENCER_AXILITES_BITS_FINAL_TOP_PTR_DATA 32
#define XSEQUENCER_AXILITES_ADDR_FINAL_TOP_PTR_CTRL 0x64
#define XSEQUENCER_AXILITES_ADDR_FINAL_BOT_PTR_DATA 0x68
#define XSEQUENCER_AXILITES_BITS_FINAL_BOT_PTR_DATA 32
#define XSEQUENCER_AXILITES_ADDR_FINAL_BOT_PTR_CTRL 0x6c

